autocmd vimenter * NERDTree

set encoding=utf-8
set number
set mouse=a
set completeopt=longest,menuone
set noshowmode
set ttymouse=xterm2
set tabstop=4
set expandtab

syntax on
filetype plugin indent on
let g:airline#extensions#tabline#enabled = 1

" Buffer navigation mapping
map bn :bn<cr>
map bp :bp<cr>
map bd :bd<cr>


" Go development configuration
let g:go_metalinter_command = "golangci-lint"
let g:go_metalinter_autosave_enabled = ['vet', 'golint', 'misspell', 'deadcode', 'varcheck']

" Build and run tests on save.
augroup auto_go
	autocmd!
	autocmd BufWritePost *.go :GoBuild
	autocmd BufWritePost *.go :GoMetaLinter
	autocmd BufWritePost *_test.go :GoTest
	autocmd BufWritePost *_test.go :GoMetaLinter
augroup end


" Ctrl-P bindings
nnoremap <silent> <C-b> :CtrlPBuffer<CR>

" go-vim bindings
nnoremap <silent> <C-r> :GoReferrers<CR>

" Status line
set statusline=%t

" Show signature help on accepting autocompletion
autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
